routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Front')->name('front.')->group(function()
{

	Route::get('/','HomeController@index')->name('get.home.index');
	Route::get('/menu','MenuController@index')->name('get.menu.index');
	Route::get('/about','StaticController@about')->name('get.static.about');
	Route::get('/contact-us','StaticController@contactUs')->name('get.static.contactUs');
	Route::post('/contact-us','StaticController@sendMessage')->name('post.static.sendMessage');
	Route::get('/press','PressController@index')->name('get.press.index');
	Route::get('/press/{slig}','PressController@show')->name('get.press.show');
});

app/Http/Controllers/Front/HomeController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Slider;
use App\Models\Testimonial;
use App\Models\Gallery;
use App\Models\Blog;
use App\Models\Team;
use App\Models\Menu;

class HomeController extends Controller
{
    public function index()
    {
    	$data['slides'] = Slider::where('show','yes')->take('3')->get();
    	$data['testi'] = Testimonial::where('show','yes')->take('3')->get();
    	$data['gallery'] = Gallery::where('show','yes')->take('5')->get();
    	$data['posts'] = Blog::where('show','yes')->take('6')->get();
    	$data['team'] = Team::where('show','yes')->take('6')->get();
    	$data['menu'] = Menu::where('show','yes')->where('show_in_homePage','yes')->take('6')->get();
    	return view('front.index')->with($data);
    }
}

app/Http/Controllers/Front/MenuController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Category;
use App\Models\Menu;

class MenuController extends Controller
{
    public function index()
    {
        $data['menu'] = Menu::where('show','yes')->where('special','yes')->take('12')->get();
    	$data['categories'] = Category::where('show','yes')->get();
    	return view('front.menu.index')->with($data);
    }
}

app/Http/Controllers/Front/PressController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


use App\Models\Blog;


class PressController extends Controller
{
    public function index()
    {
        $data['posts'] = Blog::where('show','yes')->orderBy('created_at','DESC')->paginate(6);
    	return view('front.press.index')->with($data);
    }


    public function show($slug)
    {
        $row = Blog::where('slug',$slug)->first();
        if($row)
        {
            $posts = Blog::where('show','yes')->orderBy('id','DESC')->take(6)->get();
            return view('front.press.show',compact(['row','posts']));
        }
    }
}

app/Http/Controllers/Front/StaticController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Category;
use App\Models\Menu;
use App\Models\Message;

class StaticController extends Controller
{
    public function about()
    {
    	return view('front.static.about');
    }



    public function contactUs()
    {
    	return view('front.static.contact');
    }



     // send message   
    public function sendMessage(Request $request)
    {

        if($request->ajax())
        {
            $request->validate([

                'name' => 'required|string|max:100',
                'subject' => 'required|string|max:100',
                'email' => 'required|email|max:100',
                'message' => 'required|string|max:2000',
            ]);

            $data = $request->except("_token");

            Message::create($data);
            $message['success'] = trans('front.messages.contactusMessage');
            return response()->json($message);
        }
    }



}

resources/views/front/inc/footer.blade.php
			<footer id="footer" class="border-top-0 bg-color-secondary mt-0">
				<div class="container">
					<div class="row py-5">
						<div class="col text-center">
							<ul class="footer-social-icons social-icons social-icons-clean social-icons-big social-icons-opacity-light social-icons-icon-light mt-1">

								<li class="social-icons-facebook">
									<a href="{{$setting->facebook}}" target="_blank" title="Facebook"><i class="fab fa-facebook-f"></i></a></li>

								<li class="social-icons-twitter"><a href="{{$setting->twitter}}" target="_blank" title="Twitter"><i class="fab fa-twitter"></i></a></li>
								<li class="social-icons-linkedin"><a href="{{$setting->instagram}}" target="_blank" title="Linkedin"><i class="fab fa-instagram"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="footer-copyright footer-copyright-style-2 bg-color-secondary">
					<div class="container py-2">
						<div class="row py-4">
							<div class="col-lg-8 text-center text-lg-left mb-2 mb-lg-0">
								<p>
									<span class="pr-0 pr-md-3 d-block d-md-inline-block"><i class="far fa-dot-circle text-color-primary top-1 p-relative"></i><span class="text-color-light opacity-7 pl-1">{{$setting->address}}</span></span>
									<span class="pr-0 pr-md-3 d-block d-md-inline-block"><i class="fab fa-whatsapp text-color-primary top-1 p-relative"></i><a href="tel:1234567890" class="text-color-light opacity-7 pl-1">{{$setting->whatsapp}}</a></span>
									<span class="pr-0 pr-md-3 d-block d-md-inline-block"><i class="far fa-envelope text-color-primary top-1 p-relative"></i><a href="mailto:mail@example.com" class="text-color-light opacity-7 pl-1">{{$setting->email}}</a></span>
								</p>
							</div>
							<div class="col-lg-4 d-flex align-items-center justify-content-center justify-content-lg-end mb-4 mb-lg-0 pt-4 pt-lg-0">
								<p class="text-color-light opacity-7">© Copyright <a href="https://eraasoft.com/">EraaSoft</a> 2019. All Rights Reserved.</p>
							</div>
						</div>
					</div>
				</div>
			</footer>
			
		</div>

		<!-- Vendor -->
		<script src="{{furl()}}/vendor/jquery/jquery.min.js"></script>		
		<script src="{{furl()}}/vendor/jquery.appear/jquery.appear.min.js"></script>		
		<script src="{{furl()}}/vendor/jquery.easing/jquery.easing.min.js"></script>		
		<script src="{{furl()}}/vendor/jquery.cookie/jquery.cookie.min.js"></script>		

		<script src="{{furl()}}/vendor/popper/umd/popper.min.js"></script>		
		<script src="{{furl()}}/vendor/bootstrap/js/bootstrap.min.js"></script>		
		<script src="{{furl()}}/vendor/common/common.min.js"></script>		
		<script src="{{furl()}}/vendor/jquery.validation/jquery.validate.min.js"></script>	
		<script src="{{furl()}}/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>	
		<script src="{{furl()}}/vendor/jquery.gmap/jquery.gmap.min.js"></script>		
		<script src="{{furl()}}/vendor/jquery.lazyload/jquery.lazyload.min.js"></script>	
		<script src="{{furl()}}/vendor/isotope/jquery.isotope.min.js"></script>		
		<script src="{{furl()}}/vendor/owl.carousel/owl.carousel.min.js"></script>		
		<script src="{{furl()}}/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>	
		<script src="{{furl()}}/vendor/vide/jquery.vide.min.js"></script>
		
		<!-- Theme Base, Components and Settings -->
		<script src="{{furl()}}/js/theme.js"></script>
		
		<!-- Current Page Vendor and Views -->
		<script src="{{furl()}}/vendor/rs-plugin/js/jquery.themepunch.tools.min.js"></script>		<script src="{{furl()}}/vendor/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>

		<!-- Current Page Vendor and Views -->
		<script src="{{furl()}}/js/views/view.contact.js"></script>

		
		<!-- Theme Custom -->
		<script src="{{furl()}}/js/custom.js"></script>
		
		<!-- Theme Initialization Files -->
		<script src="{{furl()}}/js/theme.init.js"></script>


		@yield('script')



	</body>

<!-- Mirrored from preview.oklerthemes.com/porto/7.0.0/demo-restaurant.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 23 Apr 2019 15:26:19 GMT -->
</html>

resources/views/front/inc/header.blade.php
<!DOCTYPE html>
<html data-style-switcher-options="{'changeLogo': false, 'borderRadius': 0, 'colorPrimary': '#e09b23', 'colorSecondary': '#344257', 'colorTertiary': '#D1E7E7', 'colorQuaternary': '#EDEADA'}">
	
<!-- Mirrored from preview.oklerthemes.com/porto/7.0.0/demo-restaurant.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 23 Apr 2019 15:24:55 GMT -->
<head>

		<!-- Basic -->
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">	

		<title>Eraa - Restaurant</title>	

		<meta name="keywords" content="HTML5 Template" />
		<meta name="description" content="Porto - Responsive HTML5 Template">
		<meta name="author" content="okler.net">

		<!-- Favicon -->
		<link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" />
		<link rel="apple-touch-icon" href="{{furl()}}/img/apple-touch-icon.png">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

		<!-- Web Fonts  -->
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="{{furl()}}/vendor/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" href="{{furl()}}/vendor/fontawesome-free/css/all.min.css">
		<link rel="stylesheet" href="{{furl()}}/vendor/animate/animate.min.css">
		<link rel="stylesheet" href="{{furl()}}/vendor/simple-line-icons/css/simple-line-icons.min.css">
		<link rel="stylesheet" href="{{furl()}}/vendor/owl.carousel/assets/owl.carousel.min.css">
		<link rel="stylesheet" href="{{furl()}}/vendor/owl.carousel/assets/owl.theme.default.min.css">
		<link rel="stylesheet" href="{{furl()}}/vendor/magnific-popup/magnific-popup.min.css">



		<!-- Theme CSS -->
		<link rel="stylesheet" href="{{furl()}}/css/theme.css">
		<link rel="stylesheet" href="{{furl()}}/css/theme-elements.css">
		<link rel="stylesheet" href="{{furl()}}/css/theme-blog.css">
		<link rel="stylesheet" href="{{furl()}}/css/theme-shop.css">

		<!-- Current Page CSS -->
		<link rel="stylesheet" href="{{furl()}}/vendor/rs-plugin/css/settings.css">
		<link rel="stylesheet" href="{{furl()}}/vendor/rs-plugin/css/layers.css">
		<link rel="stylesheet" href="{{furl()}}/vendor/rs-plugin/css/navigation.css">
		
		<!-- Demo CSS -->
		<link rel="stylesheet" href="{{furl()}}/css/demos/demo-restaurant.css">

		<!-- Skin CSS -->
		<link rel="stylesheet" href="{{furl()}}/css/skins/skin-restaurant.css">		<script src="master/style-switcher/style.switcher.localstorage.js"></script> 

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="{{furl()}}/css/custom.css">
		<link rel="stylesheet" href="{{furl()}}/css/front.css">

		<!-- Head Libs -->
		<script src="{{furl()}}/vendor/modernizr/modernizr.min.js"></script>

	</head>
	<body data-spy="scroll" data-target="#navSecondary" data-offset="170">

		<div class="body">

resources/views/front/inc/topHead.blade.php
<header id="header" class="header-effect-shrink" data-plugin-options="{'stickyEnabled': true, 'stickyEffect': 'shrink', 'stickyEnableOnBoxed': true, 'stickyEnableOnMobile': true, 'stickyChangeLogo': true, 'stickyStartAt': 120, 'stickyHeaderContainerHeight': 70}">
				<div class="header-body border-top-0">
					<div class="header-top border-bottom-0 bg-color-secondary">
						<div class="container">
							<div class="header-row py-2">
								<div class="header-column justify-content-center justify-content-md-start">
									<div class="header-row">
										<nav class="header-nav-top">
											<ul class="nav nav-pills">
												<li class="nav-item">
													<span class="text-light opacity-7 pl-0">The best place to eat in Eraa Restaurant !</span>
												</li>
											</ul>
										</nav>
									</div>
								</div>
								<div class="header-column justify-content-end d-none d-md-flex">
									<div class="header-row">
										<nav class="header-nav-top">
											<ul class="nav nav-pills">
												<li class="nav-item">
													<a href="tel:123-456-7890"><i class="fab fa-whatsapp text-4 text-color-primary" style="top: 0;"></i> {{$setting->whatsapp}}</a>
												</li>
											</ul>
										</nav>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="header-container container">
						<div class="header-row">
							<div class="header-column">
								<div class="header-row">
									<div class="header-logo">
										<a href="{{route('front.get.home.index')}}">
											<img alt="Porto" width="116" height="50" data-sticky-width="82" data-sticky-height="36" src="{{furl()}}/img/demos/restaurant/logo-restaurant.png">
										</a>
									</div>
								</div>
							</div>
							<div class="header-column justify-content-end">
								<div class="header-row">
									<div class="header-nav order-2 order-lg-1">
										<div class="header-nav-main header-nav-main-effect-1 header-nav-main-sub-effect-1">
											<nav class="collapse">
												<ul class="nav nav-pills" id="mainNav">
													<li>
														<a class="nav-link @if(Request::segment('1') == '') active @endif" href="{{route('front.get.home.index')}}">
															Home
														</a>
													</li>
													<li>
														<a 
														href="{{route('front.get.menu.index')}}" class="nav-link @if(Request::segment('1') == 'menu') active @endif">
															Menu
														</a>
													</li>
													<li>
														<a class="nav-link @if(Request::segment('1') == 'about') active @endif" href="{{route('front.get.static.about')}}">
															About
														</a>
													</li>
													<li>
														<a class="nav-link @if(Request::segment('1') == 'press') active @endif" href="{{route('front.get.press.index')}}">
															Press
														</a>
													</li>
													<li>
														<a class="nav-link @if(Request::segment('1') == 'contact-us') active @endif" href="{{route('front.get.static.contactUs')}}">
															Contact
														</a>
													</li>
												</ul>
											</nav>
										</div>
										<button class="btn header-btn-collapse-nav" data-toggle="collapse" data-target=".header-nav-main nav">
											<i class="fas fa-bars"></i>
										</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</header>