routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Front')->name('front.')->group(function()
{

	Route::get('/','HomeController@index')->name('get.home.index');
	Route::get('/menu','MenuController@index')->name('get.menu.index');
	Route::get('/about','StaticController@about')->name('get.static.about');
	Route::get('/contact-us','StaticController@contactUs')->name('get.static.contactUs');
	Route::post('/contact-us','StaticController@sendMessage')->name('post.static.sendMessage');
	Route::get('/press','PressController@index')->name('get.press.index');
	Route::get('/press/{slig}','PressController@show')->name('get.press.show');
});

app/Http/Controllers/Front/HomeController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Slider;
use App\Models\Testimonial;
use App\Models\Gallery;
use App\Models\Blog;
use App\Models\Team;
use App\Models\Menu;

class HomeController extends Controller
{
    public function index()
    {
    	$data['slides'] = Slider::where('show','yes')->take('3')->get();
    	$data['testi'] = Testimonial::where('show','yes')->take('3')->get();
    	$data['gallery'] = Gallery::where('show','yes')->take('5')->get();
    	$data['posts'] = Blog::where('show','yes')->take('6')->get();
    	$data['team'] = Team::where('show','yes')->take('6')->get();
    	$data['menu'] = Menu::where('show','yes')->where('show_in_homePage','yes')->take('6')->get();
    	return view('front.index')->with($data);
    }
}

app/Http/Controllers/Front/MenuController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Category;
use App\Models\Menu;

class MenuController extends Controller
{
    public function index()
    {
        $data['menu'] = Menu::where('show','yes')->where('special','yes')->take('12')->get();
    	$data['categories'] = Category::where('show','yes')->get();
    	return view('front.menu.index')->with($data);
    }
}

app/Http/Controllers/Front/PressController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;


use App\Models\Blog;


class PressController extends Controller
{
    public function index()
    {
        $data['posts'] = Blog::where('show','yes')->orderBy('created_at','DESC')->paginate(6);
    	return view('front.press.index')->with($data);
    }


    public function show($slug)
    {
        $row = Blog::where('slug',$slug)->first();
        if($row)
        {
            $posts = Blog::where('show','yes')->orderBy('id','DESC')->take(6)->get();
            return view('front.press.show',compact(['row','posts']));
        }
    }
}

app/Http/Controllers/Front/StaticController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Category;
use App\Models\Menu;
use App\Models\Message;

class StaticController extends Controller
{
    public function about()
    {
    	return view('front.static.about');
    }



    public function contactUs()
    {
    	return view('front.static.contact');
    }



     // send message   
    public function sendMessage(Request $request)
    {

        if($request->ajax())
        {
            $request->validate([

                'name' => 'required|string|max:100',
                'subject' => 'required|string|max:100',
                'email' => 'required|email|max:100',
                'message' => 'required|string|max:2000',
            ]);

            $data = $request->except("_token");

            Message::create($data);
            $message['success'] = trans('front.messages.contactusMessage');
            return response()->json($message);
        }
    }



}

resources/views/front/press/index.blade.php
@extends('front.main')

@section('content')

<div role="main" class="main">
				<section class="page-header page-header-modern page-header-md bg-transparent mb-0 pb-3">
					<div class="container">
						<div class="row">
							<div class="col-md-12 align-self-center p-static order-2 text-center">
								<h1 class="text-10 text-color-dark my-3">Press <strong>&amp; </strong> Events</h1>
								<p class="text-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu pulvinar magna.<br>Lorem ipsum dolor sit amet, consectetur adipiscing elit...</p>
								<hr class="custom-divider my-0">
							</div>
						</div>
					</div>
				</section>

				<section class="section section-default mb-0">
					<div class="container pb-5">

						@foreach($posts as $post)
						<div class="row">
							<div class="col">
								<div class="thumb-info thumb-info-side-image thumb-info-no-zoom thumb-info-no-borders thumb-info-blog-custom mt-5">
									<div class="thumb-info-side-image-wrapper p-0 d-none d-sm-block">
										<a title="" href="{{route('front.get.press.show',[$post->slug])}}">
											<img src="{{getImage(BLOG_PATH.$post->img)}}" class="img-fluid mr-3" alt="" style="width: 235px;">
										</a>
									</div>
									<div class="thumb-info-caption">
										<div class="thumb-info-caption-text">
											<h2 class="mb-3 mt-1"><a title="" class="text-dark" href="{{route('front.get.press.show',[$post->slug])}}">{{$post->name}}</a></h2>
											<span class="post-meta">
												<span>{{$post->created_at}} | <a href="{{route('front.get.press.show',[$post->slug])}}">John Doe</a></span>
											</span>
											<p class="text-3 p-0 pl-md-3">{{$post->small_desc}}</p>
											<a class="mt-3" href="{{route('front.get.press.show',[$post->slug])}}">Read More <i class="fas fa-long-arrow-alt-right"></i></a>
										</div>
									</div>
								</div>

							</div>
						</div>
						@endforeach
						
					</div>
				</section>
			</div>

@endsection

resources/views/front/press/show.blade.php
@extends('front.main')

@section('content')
<div role="main" class="main">
	<section class="page-header page-header-modern page-header-md bg-transparent mb-0 pb-3">
		<div class="container">
			<div class="row">
				<div class="col-md-12 align-self-center p-static order-2 text-center">
					<h1 class="text-10 text-color-dark my-3">Press <strong>&amp; </strong> Events</h1>
					<p class="text-3">{{$row->small_desc}}</p>
					<hr class="custom-divider my-0">
				</div>
			</div>
		</div>
	</section>

	<div class="container">

		<div class="row pt-2">
			<div class="col">
				<div class="blog-posts single-post mt-5">

					<article class="post post-large blog-single-post">

						<div class="post-date">
							<span class="day">{{date('d',strtotime($row->created_at))}}</span>
							<span class="month">{{date('M',strtotime($row->created_at))}}</span>
						</div>

						<div class="post-content">

							<h1 class="mb-3">Lorem ipsum dolor sit amet</h1>

							<div class="post-meta">
								<span><i class="far fa-user"></i> By <a href="#">John Doe</a> </span>
								<span><i class="far fa-folder"></i> <a href="#">Duis</a>, <a href="#">News</a> </span>
							
							</div>

							<img src="{{getImage(BLOG_PATH.$row->img)}}" class="img-fluid float-right mb-3 mb-1 ml-4" alt="" style="width: 360px;">

							{!!$row->desc!!}

							<div class="pt-2 pb-1">
								<!-- AddThis Button BEGIN -->
								<div class="addthis_toolbox addthis_default_style">
									<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
									<a class="addthis_button_tweet"></a>
									<a class="addthis_button_pinterest_pinit"></a>
									<a class="addthis_counter addthis_pill_style"></a>
								</div>
								<script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=xa-50faf75173aadc53"></script>
								<!-- AddThis Button END -->
							</div>

						</div>
					</article>

				</div>
			</div>
		</div>



		<section class="section section-default mb-0">
			<div class="container pb-5">

				@foreach($posts as $post)
				<div class="row">
					<div class="col">
						<div class="thumb-info thumb-info-side-image thumb-info-no-zoom thumb-info-no-borders thumb-info-blog-custom mt-5">
							<div class="thumb-info-side-image-wrapper p-0 d-none d-sm-block">
								<a title="" href="{{route('front.get.press.show',[$post->slug])}}">
									<img src="{{getImage(BLOG_PATH.$post->img)}}" class="img-fluid mr-3" alt="" style="width: 235px;">
								</a>
							</div>
							<div class="thumb-info-caption">
								<div class="thumb-info-caption-text">
									<h2 class="mb-3 mt-1"><a title="" class="text-dark" href="{{route('front.get.press.show',[$post->slug])}}">{{$post->name}}</a></h2>
									<span class="post-meta">
										<span>{{$post->created_at}} | <a href="{{route('front.get.press.show',[$post->slug])}}">John Doe</a></span>
									</span>
									<p class="text-3 p-0 pl-md-3">{{$post->small_desc}}</p>
									<a class="mt-3" href="{{route('front.get.press.show',[$post->slug])}}">Read More <i class="fas fa-long-arrow-alt-right"></i></a>
								</div>
							</div>
						</div>

					</div>
				</div>
				@endforeach
				
			</div>
		</section>

	</div>
</div>

@endsection